### PR TITLE
Fix handling of UnknownOperationException

### LINKED ISSUE #1751: bug: UnknownOperationException should return 400 instead of 500
## Expected behavior
`{ "operationName": "books", "variables": {}, "query": "{ books {\nid\nname\n} }" }`
When this type of request/query is submitted (note, the operationName "books" without a matching named query), an UnknownOperationException is thrown from graphql.language.NodeUtil. When an UnknownOperationException is thrown, the result should be ResponseEntity.badRequest... since it is a malformed request.

## Actual behavior
When this type of query is submitted and an UnknownOperationException is thrown, the current behavior is that an Internal Server Error is returned to the caller.

## Steps to reproduce
Submit a named query with non-matching operationName. Or submit a non-named query with any operationName specified. Or submit two named queries without an operationName specified.

### PR DESCRIPTION
**Pull request by kilink**
When GraphQL.executeAsync throws UnknownOperationException, or any exception implementing GraphQLError, set the status to BAD_REQUEST / 400 in BaseDgsQueryExecutor. Fixes #1751.

### CODE REVIEW

File: graphql-dgs/src/test/kotlin/com/netflix/graphql/dgs/internal/DefaultDgsQueryExecutorTest.kt [hunk 1]
```diff
@@ -204,6 +205,17 @@ internal class DefaultDgsQueryExecutorTest {
             .isInstanceOf(InvalidSyntaxError::class.java)
     }
 
+    @Test
+    fun `Invalid operation returns a GraphQL Error with type UnknownOperationException`() {
```
Comment (srinivasankavitha) [inline graphql-dgs/src/test/kotlin/com/netflix/graphql/dgs/internal/DefaultDgsQueryExecutorTest.kt:209]: Should we also check  that the status is set to BAD_REQUEST?

**Review by Emily — APPROVED** [review]

File: graphql-dgs/src/test/kotlin/com/netflix/graphql/dgs/internal/DefaultDgsQueryExecutorTest.kt (hunk 1 above)
Comment (kilink) [reply graphql-dgs/src/test/kotlin/com/netflix/graphql/dgs/internal/DefaultDgsQueryExecutorTest.kt:208]: I've added an assertion for that.

**Review by srinivasankavitha — APPROVED** [review]
